// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Provide a valid URI fallback for build-time static check, 
    // will be overridden by process.env.DATABASE_URL at runtime.
    url: process.env["DATABASE_URL"] || "postgresql://postgres:postgres@localhost:5432/postgres",
  },
});
